BC-MAY-21-RN/proyecto-final-pf-n21-t1

- CoAuthors
Minimun dependencies and primary setup added
Co-authored-by: danthek <abraham8507@gmail.com>
Co-authored-by: Namoku <contact@namoku.xyz>
Co-authored-by: AangelF <Aangel.Flores.R@gmail.com>
Co-authored-by: adrianagh13 <gomezhinojosa.adriana@gmail.com>
What did you implemented/Why did you implemented this:
- Explain the changes you’ve made. 
- It doesn’t need to be fancy and you don’t have to get to technical, yet. 
- Just explicit what you have implemented at a high level. 
- Let the reviewer know the overall effect of the PR.
- Reference a ticket in your issue tracker. Explain what the change is and then and only then reference the ticket.
- The “why” is a chance to explain both the engineering goal, but also a some business objective that is satisfied or moved along.
Examples:
- What?: …
> Initialize project App Dulce Hogar

- package-lock.json
- package.json
- yarn.lock
Styles components dependencies instaled
Co-authored-by: danthek <abraham8507@gmail.com>
Co-authored-by: Namoku <contact@namoku.xyz>
Co-authored-by: AangelF <Aangel.Flores.R@gmail.com>
Co-authored-by: adrianagh13 <gomezhinojosa.adriana@gmail.com>
What did you implemented/Why did you implemented this:
- Explain the changes you’ve made. 
- It doesn’t need to be fancy and you don’t have to get to technical, yet. 
- Just explicit what you have implemented at a high level. 
- Let the reviewer know the overall effect of the PR.
- Reference a ticket in your issue tracker. Explain what the change is and then and only then reference the ticket.
- The “why” is a chance to explain both the engineering goal, but also a some business objective that is satisfied or moved along.
Examples:
- What?: I've …
> Add react native styled components to app

- src/utils/buttonsMapping.js
What did you implemented/Why did you implemented this:
- Explain the changes you’ve made. 
- It doesn’t need to be fancy and you don’t have to get to technical, yet. 
- Just explicit what you have implemented at a high level. 
- Let the reviewer know the overall effect of the PR.
- Reference a ticket in your issue tracker. Explain what the change is and then and only then reference the ticket.
- The “why” is a chance to explain both the engineering goal, but also a some business objective that is satisfied or moved along.
Examples:
- What?: I've added support for authentication to implement Key Result 2 of OKR1. It includes 
model, table, controller and test. For more background, see ticket #JIRA-123.
- Why?: These changes complete the user login and account creation experience. See …
> Fix action function of button component

- src/components/atoms/Container/index.js
- src/components/atoms/Container/styled.js
- src/components/atoms/GeneralInput/styled.js
- src/components/atoms/TabRender/styled.js
- src/components/atoms/index.js
- src/components/molecules/LinkContainer/index.js
- src/components/molecules/LinkContainer/styled.js
- src/components/molecules/SignButtons/index.js
- src/components/molecules/SignButtons/styled.js
- src/components/molecules/index.js
- src/screens/Login.js
- src/screens/Path.js
- src/screens/Register.js
- src/utils/buttonsMapping.js
- src/utils/inputsMapping.js
Regenerated various styles in the Login, Register and Path screens
Co-authored-by: danthek <abraham8507@gmail.com>
Co-authored-by: Namoku <contact@namoku.xyz>
Co-authored-by: AangelF <Aangel.Flores.R@gmail.com>
- Different styles were modified in the Login, Register and Path screens.
- Replaced Stylesheets with styled components
- Regenerated components and created new ones such as Container for general View styles added in the screens mentioned before.
- close #22
> Fixed Styles for the screens

- src/components/atoms/GeneralContainer/index.js
- src/components/atoms/GeneralContainer/styled.js
- src/components/atoms/index.js
- src/screens/Recruiter/ServiceGrid.js
- src/theme/default.js
With an aqua light color this component must be used in every screen
that needs to show info.
> General component creation

- src/components/molecules/AcceptDeclineBtns/index.js
- src/components/molecules/AcceptDeclineBtns/styled.js
- src/components/molecules/UpcomingServicesComponent/index.js
- src/components/molecules/UpcomingServicesComponent/styled.js
- src/components/molecules/UpcomingServicesComponent/upcomingServiceData.js
- src/components/molecules/index.js
- src/screens/Provider/UpcomingServices.js
- src/utils/upcomingServiceMapping.js
- yarn.lock
Creation of:
-AcceptDeclineBtn Component
-UpcomingServicesComponent 
-Screen UpcomingServices
> Add UpcomingServiceComponent and Screen UpcomingServices

- src/components/atoms/ServiceStatus/index.js
- src/components/atoms/ServiceStatus/styled.js
- src/components/atoms/index.js
- src/components/molecules/ServiceGeneralCard/index.js
- src/navigation/index.js
- src/screens/Recruiter/ServicesHistory.js
- src/theme/default.js
-Add screen Service History
-Edit component GeneralCard
> Add screen Service History

- .eslintrc.js
- src/components/atoms/GeneralButton/index.js
- src/components/atoms/GeneralInput/index.js
- src/components/atoms/ServiceStatus/index.js
- src/components/molecules/CommentAndQualify/index.js
- src/components/molecules/CommentAndQualify/styled.js
- src/components/molecules/GeneralHeader/styled.js
- src/components/molecules/OneStarButton/index.js
- src/components/molecules/OneStarButton/styled.js
- src/components/molecules/OpionionComponent/index.js
- src/components/molecules/OpionionComponent/styled.js
- src/components/molecules/QualifyButton/index.js
- src/components/molecules/QualifyButton/styled.js
- src/components/molecules/ServiceGeneralCard/ServiceCardData.js
- src/components/molecules/ServiceGeneralCard/index.js
- src/components/molecules/ServiceGeneralCard/styled.js
- src/components/molecules/SignButtons/index.js
- src/components/molecules/UpcomingServicesComponent/index.js
- src/components/molecules/UpcomingServicesComponent/styled.js
- src/components/molecules/UpcomingServicesComponent/upcomingServiceData.js
- src/components/molecules/index.js
- src/navigation/index.js
- src/screens/Provider/CustomerOpinions.js
- src/screens/Provider/UpcomingServices.js
- src/screens/Recruiter/DateSelection.js
- src/screens/Recruiter/ServicesHistory.js
- src/theme/default.js
- src/utils/ServiceCardMapping.js
- src/utils/serviceButtonsMapping.js
All issue's tasks addressed.
Inserted a modal component for the customers opinions.
> Issue#28/general container and screens

- ios/Podfile
- ios/Podfile.lock
- ios/appDulceHogar/Info.plist
- package-lock.json
- package.json
- src/components/molecules/SignButtons/index.js
- src/navigation/AuthProvider.js
- src/screens/Login.js
- src/screens/Register.js
- src/theme/default.js
- yarn.lock
- Design of the button modified.
-  Authentication by GoogleSign created in the AuthProvider
- Functioning in iOS and Android
- closes #53
> Enable Google authentication 

- src/components/molecules/CommentAndQualify/index.js
- src/components/molecules/QualifyButton/index.js
- src/components/molecules/ServiceComponent/serviceButtonsData.js
- src/components/molecules/ServiceGeneralCard/index.js
- src/navigation/index.js
- src/screens/Path.js
- src/screens/Recruiter/DateSelection.js
- src/screens/Recruiter/RecruiterCreation.js
- src/screens/Recruiter/ServiceTicket.js
- src/screens/Recruiter/ServicesHistory.js
- src/screens/index.js
-Add navigation for provider screens
-Add navigation for recruiter screens
> Add navigation in all screens

- src/components/atoms/GeneralText/index.js
- src/components/atoms/GeneralText/styled.js
- src/components/molecules/MenuModal/styled.js
- src/navigation/index.js
- src/screens/Login.js
- src/screens/Recruiter/MapDirection.js
- src/screens/index.js
- src/screens/styled.js
> Map Screen Created

- src/components/atoms/ImageButton/index.js
- src/components/atoms/index.js
- src/navigation/index.js
- src/screens/Provider/ProviderCreation.js
- Component that uses Avatar from react native elements and ImagePicker library.
- Allows to upload a picture from the library.
- uri can be stored in firestore.
- closes #64
> ImageButton component

- src/components/molecules/EditData/index.js
- src/components/molecules/LinkContainer/index.js
- src/components/molecules/MenuModal/index.js
- src/components/molecules/TimePickers/index.js
- src/navigation/AuthProvider.js
- src/screens/Provider/CreationSecondary.js
- src/screens/Provider/EditDates.js
- src/screens/Provider/EditProvider.js
- src/screens/Provider/ProviderCreation.js
- src/screens/styled.js
- yarn.lock
Validations for the both screen of provider user
Google sign up won't reset the user
This pr closes #86
> Issue#86/validations and google login

- src/screens/Recruiter/DateSelection.js
- src/screens/Recruiter/ServiceTicket.js
- src/screens/styled.js
Fix style in two screens:
-Fix style in DateSelection screen.
-Fix style in ServiceTicket screen.
> Fix screen Date selection and service ticket

- package-lock.json
- package.json
- src/screens/Path.js
- src/screens/Provider/CreationSecondary.js
- src/screens/Recruiter/RecruiterCreation.js
- src/screens/Recruiter/ServiceProviders.js
- src/utils/createUserType.js
- yarn.lock
- The recruiter can save their location on firestore.
- If the recruiter previously saved their location, the screen that will render will be ServiceGrid, this validation is managed from Path.
> Issue#80/recruiter location

- src/components/molecules/GeneralHeader/index.js
- src/components/molecules/GeneralHeader/styled.js
- src/components/molecules/ProviderCard/index.js
- src/components/molecules/ServiceComponent/serviceButtonsData.js
- src/components/organisms/CardOrganism/index.js
- src/screens/Recruiter/ProviderCardData.js
- src/screens/Recruiter/ServiceProviders.js
- src/utils/serviceButtonsMapping.js
- yarn.lock
User list of the providers.
This closes #77
> Issue#77/show providers

- ios/Podfile.lock
- src/components/atoms/ImageButton/index.js
- src/components/molecules/CardButtons/index.js
- src/components/molecules/EditData/index.js
- src/components/molecules/ImageDetails/index.js
- src/components/molecules/TimePickers/index.js
- src/navigation/index.js
- src/screens/Provider/CreationSecondary.js
- src/screens/Provider/EditDates.js
- src/screens/Provider/EditProvider.js
- src/screens/Provider/ProviderCreation.js
- src/screens/Provider/ProviderPreview.js
- src/utils/createUserType.js
- src/utils/timeHook.js
- src/utils/uploadImage.js
- src/utils/userRT.js
- The provider user can upload an image from their device.
- The image is stored in the storage from firebase.
- The user can update their data including images.
- closes #87
> Issue#87/upload images firestore

- src/components/molecules/GeneralHeader/styled.js
- src/components/organisms/ProviderCardDets/index.js
- yarn.lock
-Fix icon menu position
-Add link in ProviderCard Details
Co-authored-by: danthek <abraham8507@gmail.com>
> Fix icon Menu and add a link

- src/components/molecules/GeneralHeader/index.js
- src/components/molecules/GeneralHeader/styled.js
- src/components/molecules/ProviderCard/index.js
- src/screens/Provider/EditDates.js
- src/screens/Provider/ProviderPreview.js
- src/screens/Recruiter/ProviderCardData.js
- src/screens/Recruiter/ServiceProviders.js
- src/utils/userRT.js
User preview in the provider users.
This closes #96
> Issue#96/user preview

- src/screens/Recruiter/ServiceTicket.js
Label Warning the hours needed in order for the provider to confirm the services has been removed.
> remove label from service ticket screen

- src/components/atoms/StarRating/index.js
- src/components/molecules/AcceptDeclineBtns/index.js
- src/components/molecules/AcceptedService/index.js
- src/components/molecules/BackFinishBtns/index.js
- src/components/molecules/CommentAndQualify/index.js
- src/components/molecules/QualifyButton/index.js
- src/components/molecules/ServiceGeneralCard/index.js
- src/components/organisms/ServiceClousure/index.js
- src/components/organisms/ServiceClousure/styled.js
- src/components/organisms/Services/index.js
- src/screens/Provider/CustomerOpinions.js
- src/screens/Provider/ServiceDetails.js
- src/screens/Recruiter/RecruiterCreation.js
- src/screens/Recruiter/ServiceTicket.js
- src/screens/styled.js
- src/utils/userRT.js
The recruiter and provider user can see their services and their status.
The recruiter can rate and see all the reviews.
This closes #79 and finishes the mvp.
> Issue#79/services functionality
